### ISSUE TITLE
Include PortAudio DLL with ASIO Support

### ISSUE THREAD

**Issue by feima0011** [JuliaAudio/PortAudio.jl#16] opened 2017-11-20 22:20 UTC
The PortAudio.jl is unable to detect my sound card which uses the ASIO API.
On the other hand, the PortAudio.jl  can recognize  the my sound card 
which uses WDM API. 

I think the reason is that for PortAudio to work with ASIO API, additionl
cares must be taken as suggested in the following links: 

http://portaudio.com/docs/v19-doxydocs/compile_windows_asio_msvc.html
http://portaudio.com/docs/v19-doxydocs/compile_windows.html

**Comment by ssfrr** [comment] 2017-12-11 03:08
It looks like the underlying portaudio library needs to be compiled with ASIO support. PortAudio.jl uses WinRPM.jl to install the library from the package repository, rather than building a custom one.

Can you try compiling the library or using one of the DLLs [here](https://github.com/spatialaudio/portaudio-binaries)? You should be able to swap out the DLL that WinRPM.jl installs.

**Comment by feima0011** [comment] 2017-12-11 03:57
I have compile the DLL with ASIO support on Win10. 
After replace the  default dll with the new DLL,
portaudio is able to identify the ASIO devices.

**Comment by ssfrr** [comment] 2017-12-11 04:03
Great, thanks for the update, and sorry for the delayed response. I'm going to change the name but keep the issue open, as I'd like to support ASIO devices without the end-user needing to recompile or go find a random DLL from elsewhere.

One issue is figuring out whether there are licensing issues with redistributing binaries built using the ASIO header files.

**Comment by feima0011** [comment] 2017-12-11 06:01
For my own project, I have the asio api compiled only in the DLL.
But you can compile the DLL with support to all host API
by following the link

http://portaudio.com/docs/v19-doxydocs/compile_windows.html

**Comment by feima0011** [comment] 2017-12-20 13:48
After replacing the default DLL with the new ones I compiled and the DLL compiled by others
https://github.com/spatialaudio/portaudio-binaries

PortAduio.jl become unstable, it crashes 

![device](https://user-images.githubusercontent.com/22652581/34209983-6453ccf0-e5e8-11e7-9451-7c5f096d81dd.JPG)


I do not know what to do now,  : _ :

**Comment by ssfrr** [comment] 2017-12-20 14:40
A few things would be useful to debug:

1. can you provide steps to reproduce?
2. paste the full crash output into a [gist](http://gist.github.com) - it'll be much easier to read than the screenshot.

**Comment by feima0011** [comment] 2018-01-28 00:42
The problem has been solved. 
In Julia, the array is stored in a column major mode, while 
in C, the array is stored in a row major mode.

I am not using the Julia Portaudio package, 
but call the functions defined in portaudio64bit.dll directly.

https://github.com/spatialaudio/portaudio-binaries

**Comment by ssfrr** [comment] 2018-01-28 05:32
hm, that's strange. what API are you using? PortAudio.jl takes the interleaved audio data and de-interleaves it into a column-per-channel format, but it should do that regardless of the underlying audio API that portaudio is using. I'd be curious what calls were causing your crashes and what calls you're using that don't.

**Comment by feima0011** [comment] 2018-01-28 07:09
I am using the ASIO API. 
In my project I do not use the Portaudio.jl but to use the libportaudio.jl directly.
There is something wrong with the following functions : 

  ################################################################
function Pa_ReadStream(stream::PaStream, buf::Array, frames::Integer=length(buf),
                       show_warnings::Bool=true)
    frames <= length(buf) || error("Need a buffer at least $frames long")
    err = ccall((:Pa_ReadStream, libportaudio), PaError,
                (PaStream, Ptr{Void}, Culong),
                stream, buf, frames)
    handle_status(err, show_warnings)
    buf
end
###################################################################
function Pa_WriteStream(stream::PaStream, buf::Array, frames::Integer=length(buf),
                        show_warnings::Bool=true)
    frames <= length(buf) || error("Need a buffer at least $frames long")
    err = ccall((:Pa_WriteStream, libportaudio), PaError,
                (PaStream, Ptr{Void}, Culong),
                stream, buf, frames)
    handle_status(err, show_warnings)
    nothing
end
########################################################################

Suppose we want to read or write to 8 channels, and 1024 samples to each channel.
Then the buffer size will be [ 8 row  1024 column ].

The code  **frames::Integer=length(buf)**  will give you 8096.

But the Portaudio.dll expect the sample length of each channel, that is 1024.

**Comment by ssfrr** [comment] 2018-01-28 14:52
Yeah, that's wrong. New issue: #20.

So to summarize the current state as I understand it:

1. It would be great if PortAudio.jl provided a precompiled DLL with ASIO support. That's what this issue is about.
2. You were getting a segfault, but it looks like that was an issue with your code that was bypassing the public interface.
3. #20 
4. There are some libportaudio features that you need that don't get exposed through PortAudio.jl. It'd be great if you filed a new issue so I knew what features you're using. Example code of how you're currently using them would be helpful as well.

**Comment by feima0011** [comment] 2018-01-28 23:26
In my project, I do some **real time** audio signal processing. 
I determine at each time what write to the speaker, according 
to the data I received from the microphones. 

PortAudio C program offers two methods for communicating audio data: 
(1) an asynchronous callback interface, where PortAudio calls a user 
defined callback function when new audio data is available or required, and 
(2) synchronous read and write functions which can be used in a blocking or 
non-blocking manner. 

The Portaudio.jl  provided the blocking API, but internally use the asynchronous 
callback interface provided by the C program. That cause some problems to me.
I want to 
(1) control the time when data are received, and the time when the data are output.
(2) the latency between the read and write process.

**Comment by ssfrr** [comment] 2018-01-30 22:14
Right, it makes sense that you want to use ASIO, but that doesn't require any code changes to PortAudio.jl, it just requires the right DLL (which I agree it would be great to make available by default).

I moved the discussion on API change you might need to #21, as that seems like a separate issue.

**Comment by feima0011** [comment] 2018-01-30 22:55
Yes, we need a new DLL support ASIO.

**Comment by hiccup7** [comment] 2018-08-27 16:07
I wanted to offer some Windows DLLs for PortAudio that may be helpful. These are from the Python community, but I suspect these DLLs could work for Julia. Especially important to me is that these builds support ASIO and WASAPI exclusive mode, and they use a recent version of PortAudio where WASAPI exclusive mode is working. Note that Python wheel files are ZIP format, so I use 7-Zip to extract DLLs from them.  One can also rename the extension to .zip and use Windows Explorer to extract.

These wheel files contain portaudio_x64.dll (and whatever the name is for 32-bit) compiled with the Microsoft compiler and are kept up to date:
http://www.lfd.uci.edu/~gohlke/pythonlibs/#sounddevice

The Microsoft compiler version used for each Python version is documented at https://wiki.python.org/moin/WindowsCompilers

These DLLs are built with GCC on Linux:
https://github.com/spatialaudio/portaudio-binaries/

I have tested the above DLLs on 64-bit Python 3.5/3.6 with Windows 8.1.

**Comment by ssfrr** [comment] 2018-09-15 19:44
I'm working on a new BinaryBuilder-based setup so I can do my own builds and include ASIO, etc. Hopefully in the coming weeks it should all get finished, merged, and tagged.

**Comment by feima0011** [comment] 2018-09-15 23:03
That is a good news.

The minimum latency I can achieve on windows10 using ASIO for audio is 100
samples under the sampling
frequency of 48 khz.

**Comment by bramtayl** [comment] 2021-05-25 01:24
Hi @feima0011 , can you try to see if this works on master? It looks to me that the Yggrasil script for libportaudio [here](https://github.com/JuliaPackaging/Yggdrasil/blob/master/L/libportaudio/build_tarballs.jl) includes ASIO support, so I'll tentatively close, but feel free to reopen if it doesn't work.

**Comment by ssfrr** [comment] 2021-05-25 22:14
For licensing reasons we are not able to distribute binaries with ASIO support. Users can use that build file to build it themselves though.

**Comment by bramtayl** [comment] 2021-05-25 22:22
Oops, ok, I'll reopen then

**Comment by ssfrr** [comment] 2021-06-05 01:21
It's actually probably OK to close. We're not going to be able to do anything about this.

**Closed by ssfrr** 2021-06-05 01:21 UTC
Labels: enhancement
